- name: create S3 bucket for uploaded images
  amazon.aws.s3_bucket:
    name: "{{ s3_bucket_name }}"
    endpoint_url: "{{ s3_endpoint }}"
    region: "{{ s3_region }}"
    access_key: "{{ vault_s3_access_key }}"
    secret_key: "{{ vault_s3_secret_key }}"
    state: present
    ceph: true
  delegate_to: localhost
  run_once: true